#docker-compose.yml
services:
  # Пример контейнера unbound DNS (если вам это действительно нужно):
  unbound:
    build: .
    hostname: dns2-happylink-net-ua
    container_name: unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./unbound:/etc/unbound
      - ./unbound/certs:/etc/unbound/certs
      - ./unbound/logs:/var/log/unbound
    restart: "unless-stopped"
    # mem_limit: 2g
    # memswap_limit: 2g
    # cpus: 2.0
    environment:
      - TZ=Europe/Kiev
